import Head from 'next/head'
import Header from '../components/Header'
import About from '../components/About'
import Cover from '../components/Cover'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className="bg-expaaand-pink">
      <Head>
        <title>Expaaand</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <About />
      <Cover />
      <>
      </>
      <Footer />
      
    </div>
  )
}
